<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UsuariRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuariRepository extends EntityRepository
{
    public function findReservesUsuari($usuari)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
        SELECT r FROM AppBundle:Reserva r 
        WHERE r.usuari = :id 
        ORDER BY r.diaReserva DESC');
        $consulta->setParameter('id', $usuari);

        return $consulta->getResult();
    }

}
