# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    app.manager.usuari_manager:
        class: AppBundle\Manager\UsuariManager
        arguments: ['@doctrine.orm.entity_manager', '@security.encoder_factory', '@security.token_storage']
